version: "3.3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: api:dev
    environment:
      MYSQL_HOST: db
      MYSQL_USER: vapor
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: vapor
      MYSQL_PORT: 3306
      REDIS_PASSWORD: password
      REDIS_PORT: 6379
      REDIS_HOST: redis
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    entrypoint: bash
  db:
    image: mysql:5
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: vapor
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: vapor
  redis:
    image: redis:alpine
